### PR TITLE
LSF: Commands shouldn't retry/reconnect if an error occurs

### LINKED ISSUE #79: BatchEuphoria does not handle full queues properly.
If more jobs are submitted than allowed for the user, Roddy dies with a stack trace. However, this is a BE problem and BE should throw a proper exception, which could then be catched by clients.

A workflow error occurred, try to rollback / abort submitted jobs.
bkill 14843 14844 14848 14849 14850 14852 14856
An unknown / unhandled exception occurred: 'Could not parse raw ID from: 'Group <resUsers>: Pending job threshold reached. Retrying in 60 seconds...''
de.dkfz.roddy.execution.jobs.cluster.lsf.LSFJobManager.parseJobID(LSFJobManager.groovy:611)
de.dkfz.roddy.execution.jobs.BatchEuphoriaJobManager.extractAndSetJobResultFromExecutionResult(BatchEuphoriaJobManager.groovy:143)
de.dkfz.roddy.execution.jobs.cluster.lsf.LSFJobManager.runJob(LSFJobManager.groovy:148)
de.dkfz.roddy.execution.jobs.cluster.lsf.LSFJobManager$runJob.call(Unknown Source)
de.dkfz.roddy.execution.jobs.Job.run(Job.groovy:534)
de.dkfz.roddy.knowledge.methods.GenericMethod.createAndRunSingleJob(GenericMethod.groovy:507)
de.dkfz.roddy.knowledge.methods.GenericMethod._callGenericToolOrToolArray(GenericMethod.groovy:255)
de.dkfz.roddy.knowledge.methods.GenericMethod.callGenericTool(GenericMethod.groovy:50)
de.dkfz.b080.co.files.CoverageTextFile.plot(CoverageTextFile.java:49)
de.dkfz.b080.co.files.CoverageTextFileGroup.plot(CoverageTextFileGroup.java:47)
de.dkfz.b080.co.qcworkflow.QCPipeline.execute(QCPipeline.groovy:90)
de.dkfz.roddy.core.ExecutionContext.execute(ExecutionContext.groovy:625)
de.dkfz.roddy.core.Analysis.executeRun(Analysis.java:397)
de.dkfz.roddy.core.Analysis.executeRun(Analysis.java:341)
de.dkfz.roddy.core.Analysis.rerun(Analysis.java:229)
de.dkfz.roddy.client.cliclient.RoddyCLIClient.rerun(RoddyCLIClient.groovy:513)
de.dkfz.roddy.client.cliclient.RoddyCLIClient.parseStartupMode(RoddyCLIClient.groovy:116)
de.dkfz.roddy.Roddy.parseRoddyStartupModeAndRun(Roddy.java:721)
de.dkfz.roddy.Roddy.startup(Roddy.java:289)
de.dkfz.roddy.Roddy.main(Roddy.java:216)
The reason here is an interaction of Roddy and BE. It seems BE searches for a specific line in the output that is not found. Instead returns the wait-notice above. When s.th. like this happens on the command line upon manual submission, bsub blocks.

### PR DESCRIPTION
**Pull request by askask**
Fixes #79 #132

### CODE REVIEW

File: src/main/groovy/de/dkfz/roddy/execution/jobs/cluster/lsf/LSFCommand.groovy [hunk 1]
```diff
@@ -94,6 +94,11 @@ class LSFCommand extends SubmissionCommand {
         return EMPTY
     }
 
+    @Override
+    protected String getEnvironment() {
```
Comment (vinjana) [inline src/main/groovy/de/dkfz/roddy/execution/jobs/cluster/lsf/LSFCommand.groovy]: `getEnvironmentString()` would be more appropriate.

File: src/main/groovy/de/dkfz/roddy/execution/jobs/cluster/lsf/LSFJobManager.groovy [hunk 2]
```diff
@@ -335,20 +337,19 @@ class LSFJobManager extends AbstractLSFJobManager {
 
     @Override
     protected ExecutionResult executeKillJobs(List<BEJobID> jobIDs) {
-        String command = "${LSF_COMMAND_DELETE_JOBS} ${jobIDs*.id.join(" ")}"
+        String command = "${LSF_COMMAND_ENVIRONMENT} ${LSF_COMMAND_DELETE_JOBS} ${jobIDs*.id.join(" ")}"
```
Comment (vinjana) [inline src/main/groovy/de/dkfz/roddy/execution/jobs/cluster/lsf/LSFJobManager.groovy]: Substitute direct field access by method call `environmentString`. I'd prefer that because eventually the number of retries should be configurable, modelling the environment as map is more appropriate e.g. for ProcessBuilder and a similar interface should also be used for any CommandBuilder (which we currently don't have).

File: src/main/groovy/de/dkfz/roddy/execution/jobs/cluster/lsf/LSFJobManager.groovy [hunk 3]
```diff
@@ -36,6 +36,7 @@ class LSFJobManager extends AbstractLSFJobManager {
 
     final static String TIMESTAMP_PATTERN = /${MONTH}\s+${DAY}\s+${TIME}(\s+${YEAR})?(\s+${LSF_SUFFIX})?/
 
+    static final String LSF_COMMAND_ENVIRONMENT = "LSB_NTRIES=1"
```
Comment (vinjana) [inline src/main/groovy/de/dkfz/roddy/execution/jobs/cluster/lsf/LSFJobManager.groovy]: At least for Roddy, the number of retries can probably be fixed to one. For other circumstances the number may not be appropriate and may have to be configurable.

Consider making this a `LinkedHashMap` (ordered!). Otherwise, renaming the accessor to  `getEnvironmentString()` is also an option.
